services:
  springboot:
    container_name: myclass360
    image: someupsite/someup:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev-env
    networks:
      - my_network

networks:
  my_network:
    driver: bridge